server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka

auth:
  local-server: true
  issuer-uri: http://127.0.0.1:${server.port}
  jwks-uri: ${auth.issuer-uri}/oauth2/jwks
  client-id: legacy-oauth-client
  client-secret: secret
  refresh-token-validity: 86400
  access-token-validity: 43200
  redirect-uri: https://127.0.0.1:8086/login/oauth2/code/custom

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/chinchinne_auth_1
    driver-class-name: org.mariadb.jdbc.Driver
    username: backend
    password: backend
  jpa:
#    hibernate:
#      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
    root: info